### ISSUE TITLE
Error trying the script on custom image set

### ISSUE THREAD

**Issue by eyildiz-ugoe** [POSTECH-CVLab/SCNeRF#12]
I have two streams taken from cameras aligned vertically that I have no information about. The streams look like the following:

Camera 1:
![ezgif-frame-001](https://user-images.githubusercontent.com/35396058/151793614-fff88795-5429-42b1-b9ac-766b2080dad1.png)

Camera 2:

![ezgif-frame-001](https://user-images.githubusercontent.com/35396058/151793994-6b5a5af2-dcf7-41d4-ae74-58e4434b2187.png)

where the plant rotates, so it is the only moving object in the scene. 

I wanted to give your method a try to obtain the intrinsics of these cameras (so that I can 3d reconstruct plant), and therefore turned the video streams into images (.png) and executed the following on the camera1's images:

`bash colmap_utils/colmap.sh ./images/`

However, I received an output that I could not make any sense of:

```
colmap_utils/colmap.sh: line 7: colmap: command not found
colmap_utils/colmap.sh: line 13: colmap: command not found
colmap_utils/colmap.sh: line 19: colmap: command not found
Traceback (most recent call last):
  File "/home/bla/anaconda3/envs/icn/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/bla/anaconda3/envs/icn/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/bla/Desktop/SCNeRF/colmap_utils/read_sparse_model.py", line 417, in <module>
    main()
  File "/home/bla/Desktop/SCNeRF/colmap_utils/read_sparse_model.py", line 369, in main
    cameras, images, points3D = read_model(path=model_path, ext=".bin")
  File "/home/bla/Desktop/SCNeRF/colmap_utils/read_sparse_model.py", line 305, in read_model
    cameras = read_cameras_binary(os.path.join(path, "cameras" + ext))
  File "/home/bla/Desktop/SCNeRF/colmap_utils/read_sparse_model.py", line 120, in read_cameras_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: './images/sparse/0/cameras.bin'
Post-colmap
Traceback (most recent call last):
  File "/home/bla/anaconda3/envs/icn/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/bla/anaconda3/envs/icn/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/bla/Desktop/SCNeRF/colmap_utils/post_colmap.py", line 266, in <module>
    gen_poses(args.working_dir)
  File "/home/bla/Desktop/SCNeRF/colmap_utils/post_colmap.py", line 247, in gen_poses
    poses, pts3d, perm = load_colmap_data(basedir)
  File "/home/bla/Desktop/SCNeRF/colmap_utils/post_colmap.py", line 13, in load_colmap_data
    camdata = read_model.read_cameras_binary(camerasfile)
  File "/home/bla/Desktop/SCNeRF/colmap_utils/read_sparse_model.py", line 120, in read_cameras_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: './images/sparse/0/cameras.bin'

```

What am I doing wrong?

**Comment by jeongyw12382** [comment]
Sorry for being late. I've been just back to my work after a short vacation. 

It seems COLMAP is not installed in your environment. 
Could you try the command "colmap" to check whether your environment has correctly installed the COLMAP? 
Otherwise, please follow the instruction here: https://colmap.github.io/

**Comment by jeongyw12382** [comment]
Closing the issue
