### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by 1005452649** [POSTECH-CVLab/SCNeRF#26]
Training Done
Starts Train Rendering
  0%|                                                                                                                                                                  | 0/17 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/user/linzejun01/linzejun_mutiply_view01/SCNeRF-master/NeRF/run_nerf.py", line 1047, in <module>
    train()
  File "/home/user/linzejun01/linzejun_mutiply_view01/SCNeRF-master/NeRF/run_nerf.py", line 973, in train
    rgbs, disps = render_path(
  File "/home/user/linzejun01/linzejun_mutiply_view01/SCNeRF-master/NeRF/render.py", line 157, in render_path
    rgb, disp, acc, _ = render(
  File "/home/user/linzejun01/linzejun_mutiply_view01/SCNeRF-master/NeRF/render.py", line 44, in render
    idx_in_camera_param=np.where(i_map==image_idx)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by 1005452649** [comment]
hello,Will you help me with this problem? @jeongyw12382

**Comment by 1005452649** [comment]
hello,Will you help me with this problem? @jeongyw12382

**Comment by XLxlll** [comment]
I had the same problem, how did you solve it?
